cmake_minimum_required(VERSION 3.28...4.2.3)
message(STATUS "CMake version: " ${CMAKE_VERSION} " is ok")

project(storage_engine
    VERSION 0.0
    DESCRIPTION "Мини база данных"
    LANGUAGES CXX 
)

set(MIN_GCC_COMPILER_VERSION "15.2.0")
set(MIN_CLANG_COMPILER_VERSION "21.1.8")


IF (NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    message(FATAL_ERROR ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} " is unsupported")
ENDIF()

IF (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS ${MIN_GCC_COMPILER_VERSION})
    message(STATUS "Current version of " ${CMAKE_CXX_COMPILER_ID} "is: " ${CMAKE_CXX_COMPILER_VERSION})
    message(FATAL_ERROR ${CMAKE_CXX_COMPILER_ID} " version is less " ${MIN_GCC_COMPILER_VERSION} " and is not acceptable")
ENDIF()

IF (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS ${MIN_CLANG_COMPILER_VERSION})
    message(STATUS "Current version of " ${CMAKE_CXX_COMPILER_ID} "is: " ${CMAKE_CXX_COMPILER_VERSION})
    message(FATAL_ERROR ${CMAKE_CXX_COMPILER_ID} " version is less " ${MIN_CLANG_COMPILER_VERSION} " and is not acceptable")
ENDIF()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS)

IF (NOT CMAKE_BUILD_TYPE OR CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Build type")
ELSEIF (NOT CMAKE_BUILD_TYPE STREQUAL "Release" AND
        NOT CMAKE_BUILD_TYPE STREQUAL "Debug" AND
        NOT CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    message(FATAL_ERROR "Unsupported build type")
ENDIF()

message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")

add_executable(src/main.cpp)



